name: CI

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: lint
        run: |
          yarn install
          yarn build:icons
          yarn tsm
          yarn lint:icons
          yarn build:scss
          yarn tsc
